spring:
  application:
    name: jiggly-web-bff
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict
        secure: false  #will probably need to change when using https